<a href="https://colab.research.google.com/github/lisagamilton/python_tasks_logical/blob/main/pandas_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://drive.google.com/file/d/1xbXbLi6CyIhmWTPj6_zYysNdKEsAcVLX/view?usp=sharing

https://www.kaggle.com/datasets/arashnic/hr-analytics-job-change-of-data-scientists?resource=download

In [1]:
! gdown --id 1xbXbLi6CyIhmWTPj6_zYysNdKEsAcVLX

/usr/local/lib/python3.12/dist-packages/gdown/__main__.py:139: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1xbXbLi6CyIhmWTPj6_zYysNdKEsAcVLX
To: /content/HR_analytics.zip
100% 302k/302k [00:00<00:00, 70.0MB/s]

In [2]:
! unzip /content/HR_analytics.zip

Archive:  /content/HR_analytics.zip
  inflating: aug_test.csv
  inflating: aug_train.csv
  inflating: sample_submission.csv

In [3]:
import pandas as pd
df = pd.read_csv('/content/aug_train.csv')
df

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

In [4]:
df['high_training'] = 0
df.loc[df['training_hours'] > 100, 'high_training'] = 1
df

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target,high_training
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0,0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0,0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0,0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0,0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0,0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0,0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0,0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0,0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0,1

In [5]:
df.loc[(df['gender'] == 'Female') & (df['target'] == 1),['city','education_level']]

           city education_level
19      city_13        Graduate
45      city_21         Masters
92     city_103        Graduate
129    city_103        Graduate
140     city_90         Masters
...         ...             ...
18704   city_21         Masters
18765   city_65         Masters
18773  city_103        Graduate
18921   city_21         Masters
18954   city_16        Graduate

[326 rows x 2 columns]

In [6]:
df.loc[df['education_level'].isna(),'education_level'] = 'No_info'
df.loc[df['education_level'] =='No_info']

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target,high_training
13,5826,city_21,0.624,Male,No relevent experience,NaN,No_info,NaN,2,NaN,NaN,never,24,0.0,0
39,24659,city_71,0.884,Male,No relevent experience,no_enrollment,No_info,NaN,3,NaN,NaN,never,106,0.0,1
69,4830,city_90,0.698,NaN,No relevent experience,NaN,No_info,NaN,2,NaN,Pvt Ltd,never,228,1.0,1
136,3116,city_21,0.624,Male,No relevent experience,no_enrollment,No_info,NaN,3,NaN,NaN,1,24,0.0,0
153,8241,city_16,0.910,NaN,Has relevent experience,no_enrollment,No_info,NaN,11,NaN,NaN,1,4,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19091,16684,city_83,0.923,Male,No relevent experience,Full time course,No_info,NaN,2,NaN,NaN,1,77,1.0,0
19095,15806,city_165,0.903,NaN,No relevent experience,no_enrollment,No_info,NaN,3,NaN,Public Sector,never,62,0.0,0
19100,16368,city_65,0.802,NaN,No relevent experience,no_enrollment,No_info,NaN,4,NaN,NaN,2,304,0.0,1
19118,12211,city_126,0.479,NaN,No relevent experience,no_enrollment,No_info,NaN,1,NaN,NaN,never,316,1.0,1
19142,13750,city_40,0.776,Male,Has relevent experience,no_enrollment,No_info,NaN,5,10/49,Early Stage Startup,1,26,0.0,0

In [7]:
df.loc[df['training_hours'] > 100,['city','training_hours']]

           city  training_hours
9      city_103             123
11     city_103             108
16     city_103             106
19      city_13             132
26      city_21             148
...         ...             ...
19124  city_160             119
19126   city_16             150
19135   city_65             136
19145   city_44             190
19157   city_67             127

[3868 rows x 2 columns]

In [8]:
users = df[['enrollee_id','gender','education_level']]
scores = df[['enrollee_id','training_hours','target']]

merged_df = pd.merge(users,scores,on='enrollee_id',how='left')
merged_df

       enrollee_id gender education_level  training_hours  target
0             8949   Male        Graduate              36     1.0
1            29725   Male        Graduate              47     0.0
2            11561    NaN        Graduate              83     0.0
3            33241    NaN        Graduate              52     1.0
4              666   Male         Masters               8     0.0
...            ...    ...             ...             ...     ...
19153         7386   Male        Graduate              42     1.0
19154        31398   Male        Graduate              52     1.0
19155        24576   Male        Graduate              44     0.0
19156         5756   Male     High School              97     0.0
19157        23834    NaN  Primary School             127     0.0

[19158 rows x 5 columns]

In [9]:
df.groupby('education_level')['target'].mean().sort_values(ascending=False)

education_level
Graduate          0.279790
No_info           0.226087
Masters           0.214400
High School       0.195340
Phd               0.140097
Primary School    0.133117
Name: target, dtype: float64

In [10]:
#top 3 towns/cities where is most of high_training=1
df.loc[df['high_training'] == 1,'city'].value_counts().head(3)

city
city_103    909
city_21     567
city_16     297
Name: count, dtype: int64

In [11]:
# Cleaning data
data_list = ['my',33,1.73,'test',4.6,33, 'test']

In [12]:
numbers = []
strings = []

In [13]:
for item in data_list:
  if isinstance(item, (int,float)):
    if item not in numbers: #making sure there are no duplicates
      numbers.append(item)
      print(numbers)
  elif isinstance(item,str):
    if item not in strings:
      strings.append(item)
      print(item)

my
[33]
[33, 1.73]
test
[33, 1.73, 4.6]

In [14]:
print(numbers)
print(strings)

[33, 1.73, 4.6]
['my', 'test']

In [17]:
data_list = [
    ['apple',3,1.5,'banana'],
    [7, 'apple', 4.6, 1.5],
    ['banana',2,7,'cherry']
]
data_list

[['apple', 3, 1.5, 'banana'],
 [7, 'apple', 4.6, 1.5],
 ['banana', 2, 7, 'cherry']]

In [21]:
unique_numbers = []
unique_strings = []

for sublist in data_list:
  for item in sublist:
    if isinstance(item,(int, float)):
      if item not in unique_numbers:
        unique_numbers.append(item)
        print(item)
    elif isinstance(item, str):
      if item not in unique_strings:
        unique_strings.append(item)
        print(item)

apple
3
1.5
banana
7
4.6
2
cherry

In [22]:
print(unique_numbers)
print(unique_strings)

[3, 1.5, 7, 4.6, 2]
['apple', 'banana', 'cherry']

In [24]:
#What if column names are different for join?
clients_df = pd.DataFrame({
    'ClientID':[1,2,3,4],
    'ClientName':['Alice','Bob','Charlie','David']
})

orders_df = pd.DataFrame({
    'OrderID':[101,102,103],
    'CustomerID':[1,2,1],
    'OrderTotal':[250,150,200]
})

merged_df = pd.merge(clients_df, orders_df, left_on='ClientID', right_on='CustomerID',how='left')
print(merged_df)

   ClientID ClientName  OrderID  CustomerID  OrderTotal
0         1      Alice    101.0         1.0       250.0
1         1      Alice    103.0         1.0       200.0
2         2        Bob    102.0         2.0       150.0
3         3    Charlie      NaN         NaN         NaN
4         4      David      NaN         NaN         NaN